[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_staking_k = "4gkXvCPc8GsE3bcXMJcq24Kp2vbyCwHgzxjEjBPHUG8y"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
